REM   Script: WorldCup
REM   Creates and populates the database related to GDI project about FIFA World Cup.

CREATE TABLE COPA (
    ANO VARCHAR(4),
    CONSTRAINT PK_COPA PRIMARY KEY(ANO)
);

CREATE TABLE PAIS (
  COPA_ANO VARCHAR(4),
  NOME VARCHAR(50),
  CONSTRAINT FK_PAIS_COPA FOREIGN KEY (COPA_ANO) REFERENCES COPA(ANO)
);

CREATE TABLE PATROCINADOR (
  CNPJ VARCHAR(14),
  CONSTRAINT PK_PATR PRIMARY KEY(CNPJ)	
);

CREATE TABLE FEDERACAO(
	ID VARCHAR(10),
	DIRIGENTE_ID VARCHAR(10),
  	CONSTRAINT PK_FEDERACAO PRIMARY KEY (ID),
  	CONSTRAINT FK_FEDERACAO_DIRIGENTE_ID FOREIGN KEY (DIRIGENTE_ID) REFERENCES FEDERACAO(ID)
);

CREATE TABLE SELECAO(
	FEDERACAO_ID VARCHAR(10) UNIQUE NOT NULL,
  	CODIGO VARCHAR(4),
  	UNIFORME_PRINCIPAL VARCHAR(25),
  	UNIFORME_SECUNDARIO VARCHAR(25),
  	CONSTRAINT PK_SELECAO PRIMARY KEY (CODIGO),
  	CONSTRAINT FK_FEDERACAO FOREIGN KEY (FEDERACAO_ID) REFERENCES FEDERACAO(ID)
);

CREATE TABLE ESTADIO(
	NOME VARCHAR(20),
  	END_RUA VARCHAR(30),
  	END_NUM INT,
  	END_CIDADE VARCHAR(30),
  	CONSTRAINT PK_ESTADIO PRIMARY KEY (NOME)
);

CREATE TABLE PARTIDA(
	COPA_ANO VARCHAR(4),
  	NUMERO INT,
  	FASE VARCHAR(15),
 	RESULTADO VARCHAR(10),
  	DATA_HORA TIMESTAMP,
  	SELECAO_MANDANTE_COD VARCHAR(4) NOT NULL,
  	SELECAO_VISITANTE_COD VARCHAR(4) NOT NULL,
  	ESTADIO_NOME VARCHAR(20) NOT NULL,
  	CONSTRAINT PK_PARTIDA PRIMARY KEY(COPA_ANO, NUMERO),
  	CONSTRAINT FK_ANO_COPA FOREIGN KEY(COPA_ANO) REFERENCES COPA(ANO),
  	CONSTRAINT FK_SELECAO_MANDANTE FOREIGN KEY(SELECAO_MANDANTE_COD) REFERENCES SELECAO(CODIGO),
  	CONSTRAINT FK_SELECAO_VISITANTE FOREIGN KEY(SELECAO_VISITANTE_COD) REFERENCES SELECAO(CODIGO),
  	CONSTRAINT FK_ESTADIO_NOME FOREIGN KEY(ESTADIO_NOME) REFERENCES ESTADIO(NOME)
);

CREATE TABLE TECNICO(
	ID_FIFA VARCHAR(4),
  	SALARIO FLOAT,
  	NOME VARCHAR(20),
  	CONSTRAINT PK_ID_FIFA_TECNICO PRIMARY KEY (ID_FIFA)
);

CREATE TABLE JOGADOR(
	ID_FIFA VARCHAR(4),
  	SALARIO FLOAT,
  	NOME VARCHAR(20),
  	FUNCAO VARCHAR(20),
	CONSTRAINT PK_ID_FIFA_JOGADOR PRIMARY KEY (ID_FIFA)  	
);

CREATE TABLE PARTICIPA(
	SELECAO_COD VARCHAR(4),
  	COPA_ANO VARCHAR(4),
  	COLOCACAO INT NOT NULL,
  	TECNICO_ID VARCHAR(4),
  	CONSTRAINT PK_PARTICIPA PRIMARY KEY (SELECAO_COD, COPA_ANO),
  	CONSTRAINT FK_SELECAO_COD FOREIGN KEY (SELECAO_COD) REFERENCES SELECAO(CODIGO),
  	CONSTRAINT FK_COPA_ANO FOREIGN KEY (COPA_ANO) REFERENCES COPA(ANO),
  	CONSTRAINT FK_TECNICO_ID FOREIGN KEY (TECNICO_ID) REFERENCES TECNICO(ID_FIFA)
);

CREATE TABLE JOGADOR_CONVOCADO(
	JOGADOR_ID VARCHAR(4),
  	SELECAO_COD VARCHAR(4),
  	COPA_ANO VARCHAR(4),
  	CONSTRAINT PK_JOGADOR_CONVOCADO PRIMARY KEY(JOGADOR_ID, SELECAO_COD, COPA_ANO),
  	CONSTRAINT FK_JOGADOR_CONVOCADO_ID FOREIGN KEY (JOGADOR_ID) REFERENCES JOGADOR(ID_FIFA),
  	CONSTRAINT FK_SELECAO_CONVOCADO_COD FOREIGN KEY (SELECAO_COD) REFERENCES SELECAO(CODIGO),
  	CONSTRAINT FK_COPA_CONVOCADO_ANO FOREIGN KEY (COPA_ANO) REFERENCES COPA(ANO)
);

CREATE TABLE TREINAMENTO(
	JOGADOR_ID VARCHAR(4),
  	ESTADIO_NOME VARCHAR(20),
  	DATA DATE,
  	CONSTRAINT PK_TREINAMENTO PRIMARY KEY (JOGADOR_ID, ESTADIO_NOME, DATA),
  	CONSTRAINT FK_JOGADOR_TREINAMENTO FOREIGN KEY (JOGADOR_ID) REFERENCES JOGADOR(ID_FIFA),
  	CONSTRAINT FK_ESTADIO_TREINAMENTO FOREIGN KEY (ESTADIO_NOME) REFERENCES ESTADIO(NOME)
);

CREATE TABLE PATROCINIO(
	COPA_ANO VARCHAR(4),
  	PATROCINADOR_CNPJ VARCHAR(14),
  	SELECAO_COD VARCHAR(4),
  	CONSTRAINT PK_PATROCINIO PRIMARY KEY (COPA_ANO, PATROCINADOR_CNPJ, SELECAO_COD),
  	CONSTRAINT FK_COPA_PATROCINIO FOREIGN KEY (COPA_ANO) REFERENCES COPA(ANO),
  	CONSTRAINT FK_PATROCINADOR FOREIGN KEY (PATROCINADOR_CNPJ) REFERENCES PATROCINADOR(CNPJ),
  	CONSTRAINT FK_SELECAO_PATROCINIO FOREIGN KEY (SELECAO_COD) REFERENCES SELECAO(CODIGO)
);
